# Generated by Django 6.0.2 on 2026-04-01 07:48

import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(help_text='Дата за монтаж', validators=[scheduling.models.validate_not_past], verbose_name='Дата на монтаж')),
                ('address', models.CharField(help_text='Пълен адрес където ще се извърши монтажът', max_length=500, verbose_name='Адрес на монтаж')),
                ('status', models.CharField(choices=[('scheduled', 'Планиран'), ('in_progress', 'В процес'), ('completed', 'Завършен'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, help_text='Допълнителни бележки за монтажа', verbose_name='Бележки')),
                ('orders', models.ManyToManyField(help_text='Поръчки, които ще се монтират на тази дата', related_name='installations', to='production.order', verbose_name='Поръчки')),
            ],
            options={
                'verbose_name': 'Монтаж',
                'verbose_name_plural': 'Монтажи',
                'ordering': ['installation_date'],
            },
        ),
    ]
