# Generated by Django 5.2.6 on 2026-02-17 12:55

import django.db.models.deletion
import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0003_door_materials_window_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='production.order', verbose_name='Поръчка')),
                ('scheduled_date', models.DateField(help_text='Дата за монтаж', validators=[scheduling.models.validate_not_past], verbose_name='Планирана дата')),
                ('installers_count', models.PositiveIntegerField(default=2, verbose_name='Брой монтажисти')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
            ],
            options={
                'verbose_name': 'Монтаж',
                'verbose_name_plural': 'Монтажи',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
