# Generated by Django 5.2.6 on 2026-02-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='installers_count',
        ),
    ]
