# Generated by Django 6.0.2 on 2026-02-23 11:42

import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_copy_sash_count_to_total_sashes'),
        ('scheduling', '0002_remove_installation_installers_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installation',
            options={'ordering': ['installation_date'], 'verbose_name': 'Монтаж', 'verbose_name_plural': 'Монтажи'},
        ),
        migrations.RemoveField(
            model_name='installation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='installation',
            name='address',
            field=models.CharField(default='none', help_text='Пълен адрес където ще се извърши монтажът', max_length=500, verbose_name='Адрес на монтаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='installation',
            name='installation_date',
            field=models.DateField(default='2026-02-23', help_text='Дата за монтаж', validators=[scheduling.models.validate_not_past], verbose_name='Дата на монтаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='orders',
            field=models.ManyToManyField(help_text='Поръчки, които ще се монтират на тази дата', related_name='installations', to='production.order', verbose_name='Поръчки'),
        ),
        migrations.AddField(
            model_name='installation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Планиран'), ('in_progress', 'В процес'), ('completed', 'Завършен'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='notes',
            field=models.TextField(blank=True, help_text='Допълнителни бележки за монтажа', verbose_name='Бележки'),
        ),
    ]
