# Generated by Django 6.0.2 on 2026-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('subject', models.CharField(max_length=150, verbose_name='Относно')),
                ('message', models.TextField(verbose_name='Съобщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Изпратено на')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочетено')),
            ],
            options={
                'verbose_name': 'Съобщение',
                'verbose_name_plural': 'Съобщения (Контакти)',
                'ordering': ['-created_at'],
            },
        ),
    ]
