# Generated by Django 6.0.2 on 2026-04-01 07:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Клиент')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес за монтаж')),
                ('status', models.CharField(choices=[('pending', 'Чакаща'), ('in_production', 'В производство'), ('ready', 'Готова за монтаж'), ('completed', 'Завършена'), ('cancelled', 'Отказана')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване')),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('window', 'Прозорец'), ('door', 'Врата')], max_length=10, verbose_name='Тип продукт')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(200)], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(200)], verbose_name='Височина (мм)')),
                ('sash_count', models.PositiveIntegerField(default=1, help_text='Колко крила има прозорецът/вратата (1, 2, 3...)', verbose_name='Брой крила')),
                ('opening_mechanism', models.CharField(choices=[('fixed', 'Фиксиран (без отваряне)'), ('turn', 'Въртящ (стандартно)'), ('tilt_turn', 'Въртящ и наклоняем'), ('sliding', 'Плъзгащ'), ('lift_sliding', 'Повдигащ-плъзгащ')], default='turn', help_text='Как се отваря прозорецът/вратата', max_length=20, verbose_name='Механизъм на отваряне')),
                ('opening_direction', models.CharField(choices=[('left', 'Ляво'), ('right', 'Дясно'), ('up', 'Нагоре'), ('none', 'Без посока (фиксирано)')], default='left', help_text='За врати: Ляво/Дясно | За прозорци: Ляво/Дясно (настрани) или Нагоре', max_length=10, verbose_name='Посока на отваряне')),
                ('has_mullions', models.BooleanField(default=False, help_text='Има ли делители (импости) в прозореца', verbose_name='С делители')),
                ('mullion_count', models.PositiveIntegerField(default=0, help_text='Брой вертикални делители (за 2 части = 1 делител, за 3 части = 2 делителя)', verbose_name='Брой делители')),
                ('is_equal_parts', models.BooleanField(default=True, help_text='Дали частите са равни или неравни по ширина', verbose_name='Равни части')),
                ('parts_count', models.PositiveIntegerField(default=1, help_text='На колко части е разделен прозорецът (1, 2, 3...)', verbose_name='Брой части')),
                ('parts_config', models.JSONField(blank=True, default=list, help_text='Информация за всяка част - отваряема или фикс', verbose_name='Конфигурация на частите')),
                ('custom_widths', models.JSONField(blank=True, default=dict, help_text='Ширини за неравни части', verbose_name='Ръчни ширини')),
                ('total_sashes', models.PositiveIntegerField(default=1, help_text='Колко крила има прозорецът (обикновено 1, 2 или 3)', verbose_name='Общ брой крила')),
                ('openable_sashes', models.PositiveIntegerField(default=0, help_text='Колко от крилата са отваряеми', verbose_name='Отваряеми крила')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Вид профил (Категория)')),
                ('materials', models.ManyToManyField(blank=True, related_name='custom_products', to='inventory.material', verbose_name='Вложени материали/Обков')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='production.order', verbose_name='Поръчка')),
            ],
            options={
                'verbose_name': 'Прозорец/Врата',
                'verbose_name_plural': 'Прозорци и Врати',
            },
        ),
        migrations.CreateModel(
            name='ReadyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за брой')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_products', to='production.order')),
            ],
            options={
                'verbose_name': 'Готов продукт',
                'verbose_name_plural': 'Готови продукти',
            },
        ),
    ]
