# Generated by Django 5.2.6 on 2026-02-17 12:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Име на категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Името трябва да е поне 2 символа')], verbose_name='Име на клиент')),
                ('customer_phone', models.CharField(help_text='Телефон за контакт', max_length=20, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, help_text='Имейл за контакт (незадължително)', max_length=254, null=True, verbose_name='Имейл')),
                ('delivery_address', models.CharField(help_text='Пълен адрес където ще се извърши монтажа', max_length=255, verbose_name='Адрес за монтаж')),
                ('status', models.CharField(choices=[('pending', 'Чакаща'), ('in_production', 'В производство'), ('ready', 'Готова за монтаж'), ('completed', 'Завършена'), ('cancelled', 'Отказана')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване')),
                ('notes', models.TextField(blank=True, help_text='Допълнителни бележки за поръчката', verbose_name='Бележки')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Обща цена')),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GarageDoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('sectional_standard', 'Секционна стандартна'), ('sectional_insulated', 'Секционна изолирана'), ('roller_manual', 'Ролетна ръчна'), ('roller_automatic', 'Ролетна автоматична'), ('swing_double', 'Двукрила отварна')], max_length=30, verbose_name='Модел')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(2000, message='Минималната ширина е 2000мм')], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(2000, message='Минималната височина е 2000мм')], verbose_name='Височина (мм)')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за една гаражна врата', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единица')),
                ('has_remote_control', models.BooleanField(default=False, verbose_name='С дистанционно управление')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_doors', to='production.order', verbose_name='Поръчка')),
            ],
            options={
                'verbose_name': 'Гаражна врата',
                'verbose_name_plural': 'Гаражни врати',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(600, message='Минималната ширина е 600мм')], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(1800, message='Минималната височина е 1800мм')], verbose_name='Височина (мм)')),
                ('material_type', models.CharField(choices=[('pvc', 'ПВЦ'), ('aluminium', 'Алуминий')], default='pvc', max_length=20, verbose_name='Тип материал')),
                ('door_type', models.CharField(choices=[('entrance', 'Входна врата'), ('balcony', 'Балконска врата'), ('terrace', 'Тераса врата')], default='entrance', max_length=20, verbose_name='Тип врата')),
                ('has_glass', models.BooleanField(default=False, verbose_name='Със стъкло')),
                ('glass_percentage', models.PositiveIntegerField(default=0, help_text='Процент от вратата със стъкло (0-100)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент стъкло')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='production.order', verbose_name='Поръчка')),
            ],
            options={
                'verbose_name': 'Врата',
                'verbose_name_plural': 'Врати',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shutter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shutter_type', models.CharField(choices=[('roller_manual', 'Ролетна ръчна'), ('roller_electric', 'Ролетна електрическа'), ('venetian', 'Венециански'), ('roman', 'Римски'), ('vertical', 'Вертикални')], max_length=20, verbose_name='Тип щора')),
                ('material', models.CharField(choices=[('pvc', 'ПВЦ'), ('aluminium', 'Алуминий'), ('fabric', 'Текстил'), ('wood', 'Дърво')], default='pvc', max_length=20, verbose_name='Материал')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(300, message='Минималната ширина е 300мм')], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(300, message='Минималната височина е 300мм')], verbose_name='Височина (мм)')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единица')),
                ('color', models.CharField(default='бял', max_length=50, verbose_name='Цвят')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shutters', to='production.order', verbose_name='Поръчка')),
            ],
            options={
                'verbose_name': 'Щора',
                'verbose_name_plural': 'Щори',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(help_text='Ширина на прозореца в милиметри', validators=[django.core.validators.MinValueValidator(200, message='Минималната ширина е 200мм')], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(help_text='Височина на прозореца в милиметри', validators=[django.core.validators.MinValueValidator(200, message='Минималната височина е 200мм')], verbose_name='Височина (мм)')),
                ('material_type', models.CharField(choices=[('pvc', 'ПВЦ'), ('aluminium', 'Алуминий')], default='pvc', max_length=20, verbose_name='Тип материал')),
                ('wings_count', models.PositiveIntegerField(default=1, help_text='Общ брой крила на прозореца', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Брой крила')),
                ('openable_wings', models.PositiveIntegerField(default=0, help_text='Брой крила които могат да се отварят', verbose_name='Отваряеми крила')),
                ('glass_type', models.CharField(choices=[('single', 'Единичен стъклопакет'), ('double', 'Двоен стъклопакет'), ('triple', 'Троен стъклопакет'), ('energy', 'Енергоспестяващ')], default='double', max_length=20, verbose_name='Тип стъклопакет')),
                ('has_mosquito_net', models.BooleanField(default=False, verbose_name='С комарник')),
                ('description', models.CharField(blank=True, help_text="Например: 'Хол - голям прозорец'", max_length=255, verbose_name='Описание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='production.order', verbose_name='Поръчка')),
            ],
            options={
                'verbose_name': 'Прозорец',
                'verbose_name_plural': 'Прозорци',
                'ordering': ['order', 'id'],
            },
        ),
    ]
