# Generated by Django 6.0.2 on 2026-04-01 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Потребител(Клиент)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Име на клиент (ако не е рег.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес за монтаж'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Чакаща производство'), ('in_production', 'В производство'), ('ready', 'Готова за монтаж'), ('completed', 'Завършена'), ('cancelled', 'Отказана')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Опишете накратко какво желаете (напр. 2 прозореца за спалня, 1 балконска врата)', verbose_name='Описание на желанията')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес за оглед/монтаж')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон за връзка')),
                ('status', models.CharField(choices=[('pending', 'Очаква обработка (Нова)'), ('scheduled', 'Насрочен оглед'), ('measured', 'Взети размери (Чака оферта)'), ('ordered', 'Превърната в поръчка'), ('rejected', 'Отказана')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на заявката')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка за оферта',
                'verbose_name_plural': 'Заявки за оферти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quote_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='production.quoterequest', verbose_name='Базирана на заявка'),
        ),
    ]
