# Generated by Django 5.2.6 on 2026-02-17 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shutter',
            name='order',
        ),
        migrations.CreateModel(
            name='ReadyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('garage_sectional_standard', 'Гаражна врата - Секционна стандартна'), ('garage_sectional_insulated', 'Гаражна врата - Секционна изолирана'), ('garage_roller_manual', 'Гаражна врата - Ролетна ръчна'), ('garage_roller_automatic', 'Гаражна врата - Ролетна автоматична'), ('garage_swing_double', 'Гаражна врата - Двукрила отварна'), ('shutter_roller_manual', 'Щора - Ролетна ръчна'), ('shutter_roller_electric', 'Щора - Ролетна електрическа'), ('shutter_venetian', 'Щора - Венециански'), ('shutter_roman', 'Щора - Римски'), ('shutter_vertical', 'Щора - Вертикални')], max_length=50, verbose_name='Тип продукт')),
                ('width', models.FloatField(help_text='Ширина на продукта в милиметри', validators=[django.core.validators.MinValueValidator(100, message='Минималната ширина е 100мм')], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(help_text='Височина на продукта в милиметри', validators=[django.core.validators.MinValueValidator(100, message='Минималната височина е 100мм')], verbose_name='Височина (мм)')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за един брой', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единица')),
                ('color', models.CharField(blank=True, default='бял', help_text='Цвят на продукта (незадължително)', max_length=50, verbose_name='Цвят')),
                ('has_extras', models.BooleanField(default=False, help_text='Дистанционно управление, моторизация и др.', verbose_name='С допълнителни екстри')),
                ('notes', models.TextField(blank=True, help_text='Допълнителна информация за поръчката', verbose_name='Бележки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_products', to='production.order', verbose_name='Поръчка')),
            ],
            options={
                'verbose_name': 'Готов продукт',
                'verbose_name_plural': 'Готови продукти',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='GarageDoor',
        ),
        migrations.DeleteModel(
            name='Shutter',
        ),
    ]
