# Generated by Django 5.2.6 on 2026-02-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0002_remove_shutter_order_readyproduct_delete_garagedoor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='materials',
            field=models.ManyToManyField(blank=True, help_text='Материали необходими за производството на вратата', related_name='doors', to='inventory.material', verbose_name='Използвани материали'),
        ),
        migrations.AddField(
            model_name='window',
            name='materials',
            field=models.ManyToManyField(blank=True, help_text='Материали необходими за производството на прозореца', related_name='windows', to='inventory.material', verbose_name='Използвани материали'),
        ),
    ]
