# Generated by Django 6.0.2 on 2026-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_order_customer_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Вътрешни бележки или отговор към клиента', null=True, verbose_name='Бележки от фирмата'),
        ),
    ]
