# Generated by Django 6.0.2 on 2026-02-19 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_material_id'),
        ('production', '0003_door_materials_window_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='window',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='window',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='readyproduct',
            options={'verbose_name': 'Готов продукт', 'verbose_name_plural': 'Готови продукти'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='readyproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='readyproduct',
            name='has_extras',
        ),
        migrations.RemoveField(
            model_name='readyproduct',
            name='height',
        ),
        migrations.RemoveField(
            model_name='readyproduct',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='readyproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='readyproduct',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='readyproduct',
            name='width',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Специфични настройки или бележки за категорията', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='system_offset',
            field=models.PositiveIntegerField(default=50, help_text='Разстоянието, с което профилът застъпва стъклото (стандартно 50мм)', verbose_name='Технологичен офсет (мм)'),
        ),
        migrations.AddField(
            model_name='readyproduct',
            name='name',
            field=models.CharField(default='Продукт', max_length=100, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readyproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за брой'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Адрес за монтаж'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_products', to='production.order'),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('window', 'Прозорец'), ('door', 'Врата')], max_length=10, verbose_name='Тип продукт')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(200)], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(200)], verbose_name='Височина (мм)')),
                ('glass_percentage', models.PositiveIntegerField(default=100, help_text='Останалата площ се смята за плътен панел', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент стъкло')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.category', verbose_name='Вид профил (Категория)')),
                ('materials', models.ManyToManyField(blank=True, related_name='custom_products', to='inventory.material', verbose_name='Вложени материали/Обков')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='production.order', verbose_name='Поръчка')),
            ],
            options={
                'verbose_name': 'Прозорец/Врата',
                'verbose_name_plural': 'Прозорци и Врати',
            },
        ),
        migrations.DeleteModel(
            name='Door',
        ),
        migrations.DeleteModel(
            name='Window',
        ),
    ]
