# Generated by Django 6.0.2 on 2026-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_quoterequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Имейл (ако не е регистриран)'),
        ),
    ]
