# Generated by Django 6.0.2 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_order_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quote_requests/', verbose_name='Снимка на обекта или скица с размери'),
        ),
    ]
