# Generated by Django 6.0.2 on 2026-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_window_materials_remove_window_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='glass_percentage',
        ),
        migrations.AddField(
            model_name='customproduct',
            name='opening_type',
            field=models.CharField(choices=[('fixed', 'Фиксиран (без отваряне)'), ('turn', 'Едноврилен (въртящ)'), ('tilt_turn', 'Двукрилен (въртящ и наклоняем)'), ('sliding', 'Плъзгащ'), ('lift_sliding', 'Повдигащ-плъзгащ')], default='turn', help_text='Как се отваря прозорецът/вратата', max_length=20, verbose_name='Тип отваряне'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='sash_count',
            field=models.PositiveIntegerField(default=1, help_text='Колко крила има прозорецът/вратата (1, 2, 3...)', verbose_name='Брой крила'),
        ),
    ]
