# Generated by Django 6.0.2 on 2026-02-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_material_profile_width_and_more'),
        ('production', '0005_remove_customproduct_glass_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Вид профил (Категория)'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
