# Generated by Django 6.0.2 on 2026-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_customproduct_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='has_mullions',
            field=models.BooleanField(default=False, help_text='Има ли делители (импости) в прозореца', verbose_name='С делители'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='is_equal_parts',
            field=models.BooleanField(default=True, help_text='Дали частите са равни или неравни по ширина', verbose_name='Равни части'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='mullion_count',
            field=models.PositiveIntegerField(default=0, help_text='Брой вертикални делители (за 2 части = 1 делител, за 3 части = 2 делителя)', verbose_name='Брой делители'),
        ),
    ]
