# Generated by Django 6.0.2 on 2026-02-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_customproduct_has_mullions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='openable_sashes',
            field=models.PositiveIntegerField(default=0, help_text='Колко от крилата са отваряеми', verbose_name='Отваряеми крила'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='total_sashes',
            field=models.PositiveIntegerField(default=1, help_text='Колко крила има прозорецът (обикновено 1, 2 или 3)', verbose_name='Общ брой крила'),
        ),
    ]
