# Generated by Django 6.0.2 on 2026-02-23 07:04

from django.db import migrations


def copy_sash_count_to_total_sashes(apps, schema_editor):
    """Копира данните от sash_count в total_sashes"""
    CustomProduct = apps.get_model('production', 'CustomProduct')
    for product in CustomProduct.objects.all():
        product.total_sashes = product.sash_count
        # Ако няма зададени отваряеми крила, оставяме 0
        if not product.openable_sashes:
            product.openable_sashes = 0
        product.save()


def reverse_copy(apps, schema_editor):
    """Обратна операция - връщаме данните от total_sashes в sash_count"""
    CustomProduct = apps.get_model('production', 'CustomProduct')
    for product in CustomProduct.objects.all():
        product.sash_count = product.total_sashes
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_customproduct_openable_sashes_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_sash_count_to_total_sashes, reverse_copy),
    ]
