# Generated by Django 6.0.2 on 2026-02-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_copy_sash_count_to_total_sashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='custom_widths',
            field=models.JSONField(blank=True, default=dict, help_text='Ширини за неравни части', verbose_name='Ръчни ширини'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='parts_config',
            field=models.JSONField(blank=True, default=list, help_text='Информация за всяка част - отваряема или фикс', verbose_name='Конфигурация на частите'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='parts_count',
            field=models.PositiveIntegerField(default=1, help_text='На колко части е разделен прозорецът (1, 2, 3...)', verbose_name='Брой части'),
        ),
    ]
