# Generated by Django 6.0.2 on 2026-02-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_customproduct_custom_widths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='opening_type',
        ),
        migrations.AddField(
            model_name='customproduct',
            name='opening_direction',
            field=models.CharField(choices=[('left', 'Ляво'), ('right', 'Дясно'), ('up', 'Нагоре'), ('none', 'Без посока (фиксирано)')], default='left', help_text='За врати: Ляво/Дясно | За прозорци: Ляво/Дясно (настрани) или Нагоре', max_length=10, verbose_name='Посока на отваряне'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='opening_mechanism',
            field=models.CharField(choices=[('fixed', 'Фиксиран (без отваряне)'), ('turn', 'Въртящ (стандартно)'), ('tilt_turn', 'Въртящ и наклоняем'), ('sliding', 'Плъзгащ'), ('lift_sliding', 'Повдигащ-плъзгащ')], default='turn', help_text='Как се отваря прозорецът/вратата', max_length=20, verbose_name='Механизъм на отваряне'),
        ),
    ]
