# Generated by Django 6.0.2 on 2026-04-01 07:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Име на категория')),
                ('description', models.TextField(blank=True, help_text='Специфични настройки или бележки за категорията', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Име на доставчик')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Лице за контакт')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, help_text='Допълнителна информация за доставчика', verbose_name='Бележки')),
                ('is_active', models.BooleanField(default=True, help_text='Деактивирайте доставчици, с които вече не работите', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Доставчик',
                'verbose_name_plural': 'Доставчици',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на материала')),
                ('color', models.CharField(max_length=100, verbose_name='Цвят на материала')),
                ('brand', models.CharField(blank=True, help_text='Например: REHAU, Aluplast, ETEM, Profilink', max_length=100, verbose_name='Марка/Система')),
                ('chamber_count', models.PositiveIntegerField(blank=True, help_text='Само за PVC профили (3, 5, 6, 7 камери)', null=True, verbose_name='Брой камери')),
                ('has_thermal_break', models.BooleanField(default=False, help_text='Приложимо само за алуминиеви профили', verbose_name='С термомост')),
                ('profile_type', models.CharField(blank=True, choices=[('frame', 'Каса'), ('sash', 'Крило'), ('mullion', 'Делител'), ('glazing_bead', 'Стъклодържател'), ('z_profile', 'Z-профил'), ('other', 'Друг')], help_text="Приложимо за материали от тип 'Профил'", max_length=20, verbose_name='Вид профил')),
                ('bar_length', models.PositiveIntegerField(blank=True, default=6000, help_text='Стандартна дължина на един прът', null=True, verbose_name='Дължина на прът (мм)')),
                ('profile_width', models.PositiveIntegerField(blank=True, help_text='Монтажна ширина на профила (напр. 70мм, 82мм)', null=True, verbose_name='Ширина на профил (мм)')),
                ('falz_depth', models.PositiveIntegerField(blank=True, help_text='Разстоянието от външния ръб до дъното където ляга стъклото (обикновено 18-20мм). Измерваш с ролетка.', null=True, verbose_name='Дълбочина на фалца (мм)')),
                ('wing_visible_width', models.PositiveIntegerField(blank=True, help_text='Ширина на профила минус дълбочина на фалца (напр. 80мм - 20мм = 60мм). Можеш да измериш директно или да въведеш от каталога.', null=True, verbose_name='Видима част на крило (мм)')),
                ('mullion_width', models.PositiveIntegerField(blank=True, help_text='Пълна ширина на делител/импост (обикновено 60мм)', null=True, verbose_name='Ширина на делител (мм)')),
                ('overlap', models.PositiveIntegerField(blank=True, help_text='Колко се добавя към светлия отвор (обикновено 28-30мм, общо 14+14мм от всяка страна)', null=True, verbose_name='Застъпване (мм)')),
                ('material_type', models.CharField(choices=[('profile', 'Профил'), ('glass', 'Стъклопакет'), ('accessory', 'Аксесоар'), ('hardware', 'Обков'), ('other', 'Други')], max_length=50, verbose_name='Тип на материала')),
                ('quantity_in_stock', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0, message='Наличността не може да бъде под нула!')], verbose_name='Налично количество')),
                ('unit', models.CharField(choices=[('m', 'Линеен метър'), ('sqm', 'Kвадратен метър'), ('pcs', 'Брой')], max_length=10, verbose_name='Мерна единица')),
                ('categories', models.ManyToManyField(blank=True, help_text='Изберете за кои категории е приложим материалът (PVC, Алуминий и т.н.)', related_name='materials', to='inventory.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материали',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Доставено количество', max_digits=10, verbose_name='Количество')),
                ('delivery_date', models.DateField(help_text='Кога пристигна доставката', verbose_name='Дата на доставка')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Цена на единица за тази доставка', max_digits=10, verbose_name='Цена за единица')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Номер на фактура')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inventory.material', verbose_name='Материал')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inventory.supplier', verbose_name='Доставчик')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
    ]
