# Generated by Django 5.2.6 on 2026-02-17 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на материала')),
                ('material_type', models.CharField(choices=[('profile', 'Профил'), ('glass', 'Стъклопакет'), ('accessory', 'Аксесоар'), ('hardware', 'Обков'), ('other', 'Други')], max_length=50, verbose_name='Тип на материала')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Наличността не може да бъде под нула!')], verbose_name='Количество')),
                ('unit', models.CharField(choices=[('m', 'Линеен метър'), ('sqm', 'Kвадратен метър'), ('pcs', 'Брой')], max_length=10, verbose_name='Мерна единица')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Цената не може да e <= 0!')], verbose_name='Цена за единица')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материали',
            },
        ),
    ]
