# Generated by Django 6.0.2 on 2026-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_material_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(default='бял', max_length=100, verbose_name='Цвят на материала'),
            preserve_default=False,
        ),
    ]
