# Generated by Django 6.0.2 on 2026-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_material_color'),
        ('production', '0005_remove_customproduct_glass_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='bar_length',
            field=models.PositiveIntegerField(default=6000, help_text='Стандартна дължина на един прът', verbose_name='Дължина на прът (мм)'),
        ),
        migrations.AddField(
            model_name='material',
            name='brand',
            field=models.CharField(blank=True, help_text='Например: REHAU, Aluplast, ETEM, Profilink', max_length=100, verbose_name='Марка/Система'),
        ),
        migrations.AddField(
            model_name='material',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Изберете за кои категории е приложим материалът (PVC, Алуминий и т.н.)', related_name='materials', to='production.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='material',
            name='chamber_count',
            field=models.PositiveIntegerField(blank=True, help_text='Само за PVC профили (3, 5, 6, 7 камери)', null=True, verbose_name='Брой камери'),
        ),
        migrations.AddField(
            model_name='material',
            name='has_thermal_break',
            field=models.BooleanField(default=False, help_text='Приложимо само за алуминиеви профили', verbose_name='С термомост'),
        ),
        migrations.AddField(
            model_name='material',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('frame', 'Каса'), ('sash', 'Крило'), ('mullion', 'Делител'), ('glazing_bead', 'Стъклодържател'), ('z_profile', 'Z-профил'), ('other', 'Друг')], help_text="Приложимо за материали от тип 'Профил'", max_length=20, verbose_name='Вид профил'),
        ),
        migrations.AddField(
            model_name='material',
            name='series',
            field=models.CharField(blank=True, help_text='Например: 70мм, 82мм, E-45', max_length=50, verbose_name='Серия'),
        ),
    ]
