# Generated by Django 6.0.2 on 2026-02-20 08:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_material_bar_length_material_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Име на доставчик')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Лице за контакт')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, help_text='Допълнителна информация за доставчика', verbose_name='Бележки')),
                ('is_active', models.BooleanField(default=True, help_text='Деактивирайте доставчици, с които вече не работите', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Доставчик',
                'verbose_name_plural': 'Доставчици',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.AddField(
            model_name='material',
            name='quantity_in_stock',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0, message='Наличността не може да бъде под нула!')], verbose_name='Налично количество'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Доставено количество', max_digits=10, verbose_name='Количество')),
                ('delivery_date', models.DateField(help_text='Кога пристигна доставката', verbose_name='Дата на доставка')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Цена на единица за тази доставка', max_digits=10, verbose_name='Цена за единица')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Номер на фактура')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inventory.material', verbose_name='Материал')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inventory.supplier', verbose_name='Доставчик')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
    ]
