# Generated by Django 6.0.2 on 2026-02-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier_remove_material_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Име на категория')),
                ('description', models.TextField(blank=True, help_text='Специфични настройки или бележки за категорията', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='profile_width',
            field=models.PositiveIntegerField(blank=True, help_text='Монтажна ширина на профила (напр. 70мм, 82мм)', null=True, verbose_name='Ширина на профил (мм)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Изберете за кои категории е приложим материалът (PVC, Алуминий и т.н.)', related_name='materials', to='inventory.category', verbose_name='Категории'),
        ),
    ]
