# Generated by Django 6.0.2 on 2026-02-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_material_profile_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='series',
        ),
    ]
