# Generated by Django 6.0.2 on 2026-02-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_material_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price_per_unit',
        ),
        migrations.AlterField(
            model_name='material',
            name='bar_length',
            field=models.PositiveIntegerField(blank=True, default=6000, help_text='Стандартна дължина на един прът', null=True, verbose_name='Дължина на прът (мм)'),
        ),
    ]
