# Generated by Django 6.0.2 on 2026-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_material_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='mullion_width',
            field=models.PositiveIntegerField(blank=True, help_text='Пълна ширина на делител/импост (обикновено 60мм)', null=True, verbose_name='Ширина на делител (мм)'),
        ),
        migrations.AddField(
            model_name='material',
            name='overlap',
            field=models.PositiveIntegerField(blank=True, help_text='Колко се добавя към светлия отвор (обикновено 28-30мм, общо 14+14мм от всяка страна)', null=True, verbose_name='Застъпване (мм)'),
        ),
    ]
