# Generated by Django 6.0.2 on 2026-02-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_material_mullion_width_material_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='falz_depth',
            field=models.PositiveIntegerField(blank=True, help_text='Разстоянието от външния ръб до дъното където ляга стъклото (обикновено 18-20мм). Измерваш с ролетка.', null=True, verbose_name='Дълбочина на фалца (мм)'),
        ),
        migrations.AddField(
            model_name='material',
            name='wing_visible_width',
            field=models.PositiveIntegerField(blank=True, help_text='Ширина на профила минус дълбочина на фалца (напр. 80мм - 20мм = 60мм). Можеш да измериш директно или да въведеш от каталога.', null=True, verbose_name='Видима част на крило (мм)'),
        ),
    ]
